### ISSUE TITLE
TypeError: dayjs is not a function

### ISSUE THREAD

**Issue by xwei111** [vuepress/vuepress-theme-blog#114]
node_modules/@vuepress/core/.temp/dynamic/vuepress_blog/pageSorters.js

**Comment by Kocal** [comment]
Maybe related to https://github.com/vuepress/vuepress-plugin-blog/pull/93 ?

**Comment by xwei111** [comment]
> Maybe related to [vuepress/vuepress-plugin-blog#93](https://github.com/vuepress/vuepress-plugin-blog/pull/93) ?

yes, thanks! yesterday, I have to use @vuepress/plugin-blog@1.7.1

**Comment by Gitsifu** [comment]
I have the same problem

**Comment by billyyyyy3320** [comment]
FYI, root cause might be 

webpack/webpack#4742
iamkun/dayjs#480
iamkun/dayjs#492
