### ISSUE TITLE
Domain name is out of date！！！

### ISSUE THREAD

**Issue by abscy** [vuepress/vuepress-theme-blog#133]
- [x ] I confirm that this is an issue rather than a question.

## Bug report
*The domain name ‘ulivz.com’ is out of date， so I can't read the documentation, Please fix it! Thank you.*
#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [ ] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### Other relevant information

- `npx vuepress info`:

**Comment by billyyyyy3320** [comment]
HI @abscy, It was moved to [https://vuepress-theme-blog.billyyyyy3320.com/ ](https://vuepress-theme-blog.billyyyyy3320.com/ ).
